---
version: '3'
services:
  molecule:
    image: automium/molecule:2.22-bionic
    volumes:
      - .:/root/src/ansible-ubuntu1804
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /root/src/ansible-ubuntu1804
