---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    molecule_file: "{{ lookup('env','MOLECULE_FILE') }}"
    molecule_scenario_directory: "{{ lookup('env','MOLECULE_SCENARIO_DIRECTORY') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"
  tasks:
    - name: Create molecule instance(s)
      docker_container:
        name: "{{ item.name }}"
        hostname: "{{ item.name }}"
        image: automium/testenv:bionic
        privileged: true
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:ro
          - /lib/modules:/lib/modules:ro
          - /boot:/boot:ro
        tmpfs:
          - /run
          - /run/lock
        dns_servers:
          - "1.1.1.1"
        state: started
        recreate: no
        log_driver: none
      with_items: "{{ molecule_yml.platforms }}"
